Builds without warnings, better than nothing.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4382,7 +4382,9 @@ fi
 
 if enabled nvenc; then
     cc_default="nvcc";
-    host_cc_default="nvcc";
+    host_cc_default="clang";
+    add_cflags "-I/Developer/NVIDIA/CUDA-7.0/include/";
+    check_header cuda.h || die "ERROR: cuda.h not found.";
 fi
 
 if check_pkg_config sdl SDL_events.h SDL_PollEvent; then
